---
- hosts: "localhost"
  become: true
  tasks: 
    - name: add docker repository to yum 
      yum_repository:
            name: docker
            description: docer  repository
            baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
            enabled: 1
            gpgcheck: 1
            gpgkey: https://download.docker.com/linux/centos/gpg
    - name: yum install
      package:
        name: docker-ce
        state: latest
    - name: "start proces"
      service:
              name: docker
              state: started   
