---
- hosts: "localhost"
  tasks: 
    - name: Add a group called docker
      group:
        name: docker
        state: present

    - name: Add a user cicd-runner 
      user:
          name: cicd-runner
          comment: cicd-runner

    - name: Add a user cicd-runner and add them to a group docker
      user:
          name: cicd-runner
          groups: docker
          append: yes

    - name: add docker repository to yum 
      yum_repository:
            name: docker
            description: docer  repository
            baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
            enabled: 1
            gpgcheck: 1
            gpgkey: https://download.docker.com/linux/centos/gpg
    
    - name: yum install
      package:
        name: docker-ce
        state: latest
    - name: systemd
        state: start    
